"""add_emoji_to_expenses

Revision ID: ff82d699cad5
Revises: 79eaee45e12c
Create Date: 2026-06-30 04:18:17.639846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff82d699cad5'
down_revision: Union[str, Sequence[str], None] = '79eaee45e12c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('emoji', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'emoji')
    # ### end Alembic commands ###
